### ISSUE TITLE
how to insall/set-up

### ISSUE THREAD

**Issue by woody166** [sairon/esphome-nspanel-lovelace-ui#1]
Hi Jan,

can you provide details on the process to go through to set this up.

what files are needed to flash device with ESPHome, and then what?

**Comment by spike886** [comment]
I added an example configuration on this [PR](https://github.com/sairon/esphome-nspanel-lovelace-ui/pull/4) that may be useful for you

**Comment by sairon** [comment]
The general process is documented in [ESPHome docs](https://esphome.io/) (see the "Getting started" section) - with example configuration added to the repo now thanks to @spike886, I'm closing this issue.
