### ISSUE TITLE
[Feature Request] Custom action after arm or disarm alarm

### ISSUE THREAD

**Issue by blackscreener** [sairon/esphome-nspanel-lovelace-ui#10]
I want to connect NSPanel directly to alarm system (Ropam or RPI based alarm) without wifi connection. Can I make custom action (relay or serial command) after arm or disarm alarm on NSPanel?

**Comment by sairon** [comment]
You can add a custom `on_incoming_message` handler that would parse the payload from the touchscreen when alarm is armed/disarmed and do the appropriate action. This component is rather agnostic for the protocol between NSPanel firmware and AppDaemon app, so it's not something I'm planning to implement in the ESPHome component configuration.
