### ISSUE TITLE
HMI file too big ?

### ISSUE THREAD

**Issue by konceptnet** [sairon/esphome-nspanel-lovelace-ui#3]
Nspanel have only 4MB flash but the HMI file is 7.8MB.
Hown can I install it on the nspanel ?

**Comment by sairon** [comment]
HMI file is not saved to the flash connected to the ESP32, yet it's uploaded over a proprietary UART protocol to the Nextion display, which has a separate firmware and flash memory.

Moreover, ESPHome can only use flash memory up to the size defined in the [partition table](https://docs.platformio.org/en/latest/platforms/espressif32.html#partition-tables), which is by default 1.25 MiB (1310720 bytes). Thankfully, if you don't try to integrate too many ESPHome components in the configuration, you should be fine with that ;)
